spring:
  data:
    mongodb:
      database: vehicles
      auto-index-creation: true
      uri: "mongodb://localhost:27017/vehicles?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000"
server:
  port: 8080